### ISSUE TITLE
Submission screen - headers

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#10]
**Summary:**
1. Insert a line break before "Details" title/header
2. rename "Details" to "Comic Book Information" and underline it
3. After "Issue Cover Date" line please insert a line break, then an additional underlined heading: "Comic Book Grading Details"
4. Insert a line break before overall letter grade
5. Make "Overall Letter Grade" heading as big as the new "Comic Book Information" header from point 2 and underline it

**Comment by bartmika** [comment]
@rodolfomartinez Some variation of this was implemented.
