### ISSUE TITLE
Make Breadcrumbs better UX for mobile

### ISSUE THREAD

**Issue by bartmika** [LuchaComics/cps-frontend#101]
This is our breadcrumbs under mobile.

![Screenshot 2023-09-07 at 5 43 34 PM](https://github.com/LuchaComics/cps-frontend/assets/5767602/c4c1b6f2-63e7-4e32-8e72-7c99a4a74bc0)

However according to the [UX experts](https://www.nngroup.com/articles/breadcrumbs/) this violates a good user experience.

Therefore fix all the breadcrumbs so they look like this:

![best-buy-breadcrumb-combined](https://github.com/LuchaComics/cps-frontend/assets/5767602/12e88c35-91e1-4fb9-a1fc-1b0346160459)

**Comment by rodolfomartinez** [comment]
Fixed.
