### ISSUE TITLE
Add field AFTER CPS Exclusive option

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#113]
**Summary:

This should be added AFTER CPS Exclusive option, as a dropdown that simply reads
Which printing is this? 
(dropdown)
1st Print (selected by default)
2nd Print
3rd print
4th print
5th print
6th print
7th print
8th print
9th print
10th print
Ashcan
Unknown

(this field is mandatory, but 1st Print should be selected by default)

**Comment by rodolfomartinez** [comment]
This field does not appear when going back to edit a submission.

**Comment by bartmika** [comment]
@rodolfomartinez Confirmed bug! Issue fixed.

**Comment by rodolfomartinez** [comment]
Fixed.
