### ISSUE TITLE
Online Submissions header

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#123]
**Summary:**
At this URL
https://cpsapp.ca/submissions/comics

please change header to
Online Comic Submissions for: (insert store name)
so that it is clear that they are only viewing their submissions

**Comment by rodolfomartinez** [comment]
The label is correct but still need to append the store name, so that it displays as
Online Comic Submissions for: <insert store name>

**Comment by rodolfomartinez** [comment]
I still see this, although this is as CPS org 
<img width="1131" alt="Screenshot 2023-09-24 at 7 25 12 AM" src="https://github.com/LuchaComics/cps-frontend/assets/7537946/03023082-144a-4501-b7c9-9c4f3d56a912">

**Comment by bartmika** [comment]
What I purpose is the following:

1. When no org is selected from the filters, you see this:

![Screenshot 2023-09-24 at 9 43 16 PM](https://github.com/LuchaComics/cps-frontend/assets/5767602/0241294d-f495-402b-99d4-73dcd2da7d33)

2. However once org selected then you see it.

![Screenshot 2023-09-24 at 9 58 57 PM](https://github.com/LuchaComics/cps-frontend/assets/5767602/92af3f14-cc50-4076-bde0-118cfeeef426)

**Comment by rodolfomartinez** [comment]
@bartmika this is perfect for CPS, but if a non CPS org is logged in then should just be that stores name.

**Comment by rodolfomartinez** [comment]
Hi, the filter GUi updates and shows submissions correctly, but the table does not update to reflect the filter chosen.
<img width="1331" alt="Screenshot 2023-09-25 at 12 08 11 AM" src="https://github.com/LuchaComics/cps-frontend/assets/7537946/49030db3-ae7d-4cbd-af03-e564d5be0a55">

**Comment by bartmika** [comment]
@rodolfomartinez Confirmed that `organization` filter did not work - now fixed.

**Comment by rodolfomartinez** [comment]
Fixed.
