### ISSUE TITLE
Add step after signup - require admin approval

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#138]
**Summary:**
It would be helpful to require CPS approval for newly created retail partner accounts. I would envision the following:

signup process happens the exact same way that it currently does, with this addition:

Once the user has clicked the email verification link, the popup says:

"Your application has been forward to CPS staff, and will be processed within 1 business day."

If the user tries to login again, they should receive the following error message:

"Your application is pending approval"

Meanwhile, CPS should receive an email to info@cpscapsule.com as follows:

Subject: New CPS Retail Partner Application

Body:
There is a new CPS Retail Partner Application to review. Please click this link to view it:

This should go to profile, and within an Enable/Disable button
(this could function like "archiving")

Even if archived/disabled, submissions, customers and all data should be viewable.

**Comment by bartmika** [comment]
![Screenshot 2023-09-20 at 11 02 22 PM](https://github.com/LuchaComics/cps-frontend/assets/5767602/02e5c112-6582-4c84-8d85-709f18762e30)

**Comment by rodolfomartinez** [comment]
Fixed.
