### ISSUE TITLE
What happens to archived submissions?

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#158]
**Summary:**
Archiving a submission concerns me; nothing should ever really be deleted. if a mistake is made, since people are paying for sbumissions, edits should be able to fix most errors.

**Comment by bartmika** [comment]
Okay, I can remove the ability to archive

**Comment by rodolfomartinez** [comment]
@bartmika archived option still appears in GUI - this is logged in as CPS. Please remove. ![image](https://github.com/LuchaComics/cps-frontend/assets/7537946/214536f2-705e-4b60-b685-a5c89a9fa64c)

**Comment by rodolfomartinez** [comment]
Fixed.
