### ISSUE TITLE
U-Grade - Signature - Level 3 Only

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#161]
**Summary:**
Level 3 Retail partners may add signature data to their submissions

**Comment by bartmika** [comment]
What service type is this for? `CPS Capsule Signature Collection`?

Retailer only has options of picking CBFF or U-Grade.

**Comment by rodolfomartinez** [comment]
@bartmika this would be a new service - Signature Collection U-Grade, but again only for Level 3

**Comment by bartmika** [comment]
@rodolfomartinez Okay that makes sense, thank you. Do you have a template of this label?

**Comment by rodolfomartinez** [comment]
@bartmika I believe that this depends on #159

**Comment by rodolfomartinez** [comment]
@bartmika - made a retailer Level 3, they should have a service type called CPS U-Grade Signature Collection in the dropdown which would be a C-Capsule with signature fields enabled. I don’t see anything like this.

**Comment by rodolfomartinez** [comment]
Fixed.
