### ISSUE TITLE
Clicking view submissions gives error

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#163]
**Summary:**
Logged in as admin and clicked submissions, received this error:

<img width="1007" alt="Screenshot 2023-09-26 at 9 51 15 AM" src="https://github.com/LuchaComics/cps-frontend/assets/7537946/5e439382-3d11-44d3-a512-d7ca0e0ba564">

**Comment by bartmika** [comment]
Please move this GUI from users to organization

**Comment by rodolfomartinez** [comment]
Fixed.
