### ISSUE TITLE
Organization status for CPS

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#164]
**Summary:**
CPS staff should NOT be able to change org status on edit screen for CPS org; it should always be active.

**Comment by bartmika** [comment]
@rodolfomartinez heads up for this issue, I also included the name - so now the user cannot edit the CPS organization name.

**Comment by rodolfomartinez** [comment]
@bartmika the status still appears to be editable

**Comment by bartmika** [comment]
Note: @rodolfomartinez - Part of user registration, the CPS staff need to "review" the organization and then change the status from "pending" to "active".  By disabling status this conflicts with this flow.

**Comment by rodolfomartinez** [comment]
@bartmika this ticket is only for the CPS org; in theory a staff member could enter and "Disable" CPS admin access

**Comment by bartmika** [comment]
![Screenshot 2023-10-01 at 9 21 37 PM](https://github.com/LuchaComics/cps-frontend/assets/5767602/8889e510-acc3-46d0-8d3c-12dfec4435f9)
I confirm CPS main org is not edible for status.

**Comment by rodolfomartinez** [comment]
Complete.
