### ISSUE TITLE
New Status needed

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#171]
**Summary:**
We require a new status that will apply to retailer submissions only, and at launch will ONLY apply to Pre-screening service.

This status is: Completed by Retail Partner

**Comment by rodolfomartinez** [comment]
Depends on #196

**Comment by bartmika** [comment]
Issue fixed, give it another try @rodolfomartinez

**Comment by rodolfomartinez** [comment]
Fixed.
