### ISSUE TITLE
Status for Pre-Screening by Retail Partner

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#172]
**Summary:**
If a retail partner creates a pres-screening submission, then the status should automatically become "Completed by Retail Partner" as these submissions never make their way to CPS org; this is just a free grading tool for the stores to use.

**Comment by bartmika** [comment]
@rodolfomartinez If I understood this issue, turn off notifications to CPS staff if retailer created pre-screening.

**Comment by rodolfomartinez** [comment]
yes, notifications should not occur, but also require the status indicated above.

**Comment by rodolfomartinez** [comment]
@bartmika this depends on #171

**Comment by rodolfomartinez** [comment]
Fixed.
