### ISSUE TITLE
Pedigree Label: key issue details

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#220]
**Summary:**
using Arial (bold) 13, please place key issue details, using these coordinates in points:
x: 282.4 pt
y: 202.6 pt

**Comment by rodolfomartinez** [comment]
@bartmika this is very close. If you can confirm that the x is 282.4pt then please close

**Comment by rodolfomartinez** [comment]
@bartmika this is not generating when key issue details/dropdowns are used. Please check

**Comment by bartmika** [comment]
@rodolfomartinez confirmed - here is the fix

**Comment by rodolfomartinez** [comment]
Done
