### ISSUE TITLE
Submission ID format

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#29]
**Summary:**
begin IDs at
788346-26649-1000 - next number 788346-26649-1001, etc.

**Comment by bartmika** [comment]
No need to worry about this, this is using [`ObjectID`](https://www.mongodb.com/docs/manual/reference/method/ObjectId/) implementation from `mongodb` so it's working accordingly.

**Comment by rodolfomartinez** [comment]
@bartmika we need to follow the ID that I followed above for label printing purposes
