### ISSUE TITLE
Confirmation Email

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#33]
**Summary:**
To increase deliverability, the email should b in the structure of xyz@mg.cpsapp.ca - need to use the mg. subdomain.

Also, can the user be info, and the reply to address be info@cpsapp.ca ?

**Comment by bartmika** [comment]
Unfortunately we can but that also means that `info@mg.cpsapp.ca` will receive the messages as well. I will change it to `no-reply` using the `mg.cpsapp.ca` domain and close this issue.
