### ISSUE TITLE
email format/sender

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#41]
**Summary:**
emails should come from
info@mg.cpsapp.ca

and reply to address should be
info@cpsapp.ca

**Comment by bartmika** [comment]
@rodolfomartinez There's no option to provide a reply. Would you like this inside the email?

**Comment by rodolfomartinez** [comment]
OK then can we just make the emails come from
info@mg.cpsapp.ca?

**Comment by rodolfomartinez** [comment]
actually this is fine, let's close
