### ISSUE TITLE
Index page needs to be a registry page

### ISSUE THREAD

**Issue by bartmika** [LuchaComics/cps-frontend#50]
[ ] Index is just login page.
[ ] Inside app has "Registry" in menu
[ ] Inside app has "Registry" which you can look up `cpsn` and return select fields
[ ] Fields to return: date issued, title, volume, issue number, comic cover date, signs of restoration (yes/no), special notes, grading notes, overall grade
[ ] Have public page as well (?)

**Comment by rodolfomartinez** [comment]
@bartmika the registry should be a menu item and tile on dashboard

**Comment by rodolfomartinez** [comment]
and we don't need the registry to be on index page, it can be an item like submissions, customers etc. Also, for this part of the app, would an API be possible so we can embed the registry into something like a wordpress site down the road?
