### ISSUE TITLE
Do Orgs have multi users?

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#58]
**Summary:**
I see that Orgs and users seem to be two distinct things. Does this mean that an org can have multiple users? If so, how do they add them?

**Comment by bartmika** [comment]
When you "Add User", I've added "Role" so you can choose "staff" or "customer".

For the staff to log on, I'll just need to add change password operation.

**Comment by rodolfomartinez** [comment]
OK, so does this then mean that 
a) a customer is tied to a specific shop
and
b) could that customer be "unattached" or moved to another shop?
