### ISSUE TITLE
CPS - ugrade rules

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#74]
**Summary:**
The label has been emailed. Ugrade should only be used when a retail partner makes a submission and assigns either a letter grade OR uses the CPS percentage scale.

**Comment by bartmika** [comment]
Sorry I may need more details. Let's a schedule a call to discuss.

**Comment by rodolfomartinez** [comment]
to clarify, if a label is being generated by CPS staff, then it cannot be the one with the ugrade icon. If the label is being generated by anyone else, then it MUST be the label with the ugrade icon.
