### ISSUE TITLE
S3 error when editing entry?

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#76]
**Summary:**
When trying to edit an entry that was a duplicate ( as indicated in previous issue) receiving this errorL:
<img width="1069" alt="Screenshot 2023-06-29 at 11 07 39 PM" src="https://github.com/LuchaComics/cps-frontend/assets/7537946/2db5e1e8-82c2-4a45-8765-636ffa16a449">

**Comment by bartmika** [comment]
This issue was created when DigitalOCean had a problem with block storage.
