### ISSUE TITLE
New question before “Key Details”

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#84]
**Summary:**
need to add a question before Key Details box. Radio yes/no

Is this a key issue?

**Comment by bartmika** [comment]
@rodolfomartinez appoligies but what is a "key detail"? Need clarification.

**Comment by rodolfomartinez** [comment]
@bartmika remember the field “Special Details” - due to confusion with “Special Notes” decided to rename to “Key Details”
