### ISSUE TITLE
Service: Indie Gem Mint

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#86]
**Summary:**
If this service is selected, then the label if the Indie Gem Mint, grade is 10 (the text label beneath should read "Gem Mint") and the web form should populate n/m for all grading criteria, and answer "No" to the "Near Mint +" question, and select the CPS number scale for the grade scale and select 10.0 as the grade

Note: if this item has signature data, it is STILL an Indie Gem Mint label

**Comment by bartmika** [comment]
if this service is selected, then 

[ ] the label if the Indie Gem Mint, 
[ ] grade is 10 (the text label beneath should read "Gem Mint") 
[ ] and the web form should populate n/m for all grading criteria, 
[ ] and answer "No" to the "Near Mint +" question, 
[ ] and select the CPS number scale for the grade scale and select 10.0 as the grade
[ ] Note: if this item has signature data, it is STILL an Indie Gem Mint label
