### ISSUE TITLE
Option missing for non CPS Org submissions - Pedigree

### ISSUE THREAD

**Issue by rodolfomartinez** [LuchaComics/cps-frontend#98]
**Summary:**
This dropdown also requires the following option to be added:
CPS Pedigree U-Grade
<img width="281" alt="Screenshot 2023-09-07 at 10 52 30 AM" src="https://github.com/LuchaComics/cps-frontend/assets/7537946/42dcfd47-b45b-481b-b658-febc8f264590">

**Comment by bartmika** [comment]
For me to implement this, I'll need a "CPS Pedigree U-Grade" template document to use. Please send me this template and assign me back this ticket.
